# Generated by Django 4.1.7 on 2023-06-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='userid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
